spring.application.name=backend
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=backend
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer= org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.auto-offset-reset=latest
app.kafka.topics.system-metrics=system-metrics
app.kafka.topics.fault-alerts=fault-alerts
app.kafka.topics.frequency-alerts=frequency-alerts
app.sse.heartbeat-ms=15000
logging.level.org.springframework.kafka=INFO
logging.level.org.apache.kafka=INFO
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:2345/network_monitoring?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CET
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.show-sql=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.properties.hibernate.format_sql=true
